version: '3.8'

services:
  oracle-db:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      ORACLE_RANDOM_PASSWORD: "y"
    volumes:
      - ./database/init_scripts:/container-entrypoint-initdb.d

  spring-boot-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - oracle-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-db:1521/FREEPDB1
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test
    volumes:
      - ./keystore.p12:/app/keystore.p12
    ports:
      - "8443:8443"

  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: https://localhost:8443/api
    ports:
      - "3000:80"
