ALTER SESSION SET "_ORACLE_SCRIPT"=true;
ALTER SESSION SET CONTAINER=FREEPDB1;

CREATE USER filip IDENTIFIED BY pass123 QUOTA UNLIMITED ON USERS;
CREATE USER TEST IDENTIFIED BY test QUOTA UNLIMITED ON USERS;



